name: Mdformat
on:
  - pull_request
jobs:
  mdformat:
    name: Mdformat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Mdformat
        uses: ydah/mdformat-action@main
        with:
          number: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
